/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.*;
import controlador.*;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class VistaFactura extends javax.swing.JFrame {

    private Venta venta;
    private Turno turno;
    private Cliente cliente;
    private DefaultTableModel modeloTabla1 = new DefaultTableModel();
    private Controlador controlador;
    private Tienda tienda;
    /**
     * Creates new form VistaFacturar
     */
    public VistaFactura() {
        initComponents();
    }
    public VistaFactura(Tienda tienda){
        initComponents();
        this.setExtendedState(JFrame.ICONIFIED);
        setVisible(true);
        this.setTienda(tienda);
        iniciar(tienda);
    }
    public Venta getVenta() {
        return venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    public Turno getTurno() {
        return turno;
    }

    public void setTurno(Turno turno) {
        this.turno = turno;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public Tienda getTienda() {
        return tienda;
    }

    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }
    
    public void mostrarDetaVenta(Venta v) {
        System.out.println(v.getLineasVenta().get(0).getProducto().getNombre());
        modeloTabla1.setColumnCount(0);
        modeloTabla1.setNumRows(0);
        modeloTabla1.addColumn("Codigo");
        modeloTabla1.addColumn("Nombre");
        modeloTabla1.addColumn("Cantidad");
        modeloTabla1.addColumn("Precio");
        for (int i = 0; i < v.getLineasVenta().size(); i++) {
            Object[] fila = new Object[4];
            fila[0] = v.getLineasVenta().get(i).getProducto().getId_Producto();
            fila[1] = v.getLineasVenta().get(i).getProducto().getNombre();
            fila[2] = v.getLineasVenta().get(i).getCantidad();
            fila[3] = v.getLineasVenta().get(i).getSubTotal();
            modeloTabla1.addRow(fila);
        }
        jTableDetaVenta.setModel(modeloTabla1);
        jTableDetaVenta.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableDetaVenta.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableDetaVenta.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTableDetaVenta.getColumnModel().getColumn(3).setPreferredWidth(50);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetaVenta = new javax.swing.JTable();
        JTextFieldImpNeto = new javax.swing.JTextField();
        jTextFieldImpTotal = new javax.swing.JTextField();
        jTextFieldMoneda = new javax.swing.JTextField();
        jTextFieldTipoCambio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabelNombreFantasia = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCiut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Detalles de la Venta");

        jLabel6.setText("Totales: ");

        jLabel7.setText("ImpNeto");

        jLabel8.setText("ImpTotal");

        jLabel9.setText("Moneda:");

        jLabel10.setText("Tipo de Cambio:");

        jTableDetaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Precio Unitario", "Cantidad", "Cantidad"
            }
        ));
        jTableDetaVenta.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTableDetaVenta);
        jTableDetaVenta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        JTextFieldImpNeto.setText("jTextField2");

        jTextFieldImpTotal.setText("jTextField3");

        jTextFieldMoneda.setText("PES");

        jTextFieldTipoCambio.setText("1");

        jLabelNombreFantasia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelNombreFantasia.setText("nombreF");

        jLabelDireccion.setText("direccion");

        jLabel1.setText("CIUT:");

        jLabelCiut.setText("CIUT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel7)
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(JTextFieldImpNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jTextFieldImpTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldTipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabelNombreFantasia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCiut))
                            .addComponent(jLabelDireccion))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombreFantasia)
                .addGap(10, 10, 10)
                .addComponent(jLabelDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelCiut))
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTextFieldImpNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldImpTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldImpNeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCiut;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombreFantasia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDetaVenta;
    private javax.swing.JTextField jTextFieldImpTotal;
    private javax.swing.JTextField jTextFieldMoneda;
    private javax.swing.JTextField jTextFieldTipoCambio;
    // End of variables declaration//GEN-END:variables

    private void iniciar(Tienda tienda) {
        jLabelNombreFantasia.setText(tienda.getNombreFantasia());
        jLabelDireccion.setText(tienda.getDomicilio());
        jLabelCiut.setText(""+tienda.getCuit());
        for (int i = 0; i < tienda.getTerminal().getVenta().getLineasVenta().size(); i++) {
            jTableDetaVenta.setValueAt(tienda.getTerminal().getVenta().getLineasVenta().get(i).getProducto().toString(), i, 0);
            jTableDetaVenta.setValueAt(tienda.getTerminal().getVenta().getLineasVenta().get(i).getProducto().getPrecio(), i, 1);
            jTableDetaVenta.setValueAt(tienda.getTerminal().getVenta().getLineasVenta().get(i).getCantidad(), i, 2);
            jTableDetaVenta.setValueAt(tienda.getTerminal().getVenta().getLineasVenta().get(i).getSubTotal(), i, 3);
            DefaultTableModel tabla = (DefaultTableModel) jTableDetaVenta.getModel();
            tabla.addRow(new Object []{ "" , "" , "" , ""});
            jTextFieldImpTotal.setText(""+tienda.getTerminal().getVenta().getTotal());
            JTextFieldImpNeto.setText(""+tienda.getTerminal().getVenta().getTotal());
        }
    }
}
